In [21]:
import pandas as pd
import sys
import csv

hits="/home/luisasantus/Desktop/crg_cluster/data/structural_regression/homfam/pdbs/structures/search_hits/mmseqs/GEL-ref/GEL-ref.PDB/hits.m8"
output = "/home/luisasantus/Desktop/test"

In [2]:
df = pd.read_csv(template, sep='\s', header = None, engine = "python")
df["newname"] = df[0].str.replace(">", "")
df = df[df[2] != df["newname"]]
if not df.empty: 
    df["line"] = df.apply(lambda row : "ln -s \""+row[2]+".pdb\" \""+row["newname"]+".pdb\"", axis=1)
    df["line"].to_csv(output, sep=" ", header=None, index=False, quoting=csv.QUOTE_NONE, escapechar=",")

In [22]:
df = pd.read_csv(hits, sep='\t', header = None)

In [23]:
df[0].value_counts()

1yagg     49
2vil      49
1d0na1     5
1svr       3
Name: 0, dtype: int64

In [16]:
# 1 - Get all the sequences with maximum identity
df_grouped = df.groupby([0]).agg({2:'max'})
df_grouped = df_grouped.reset_index()
df_grouped = df_grouped.rename(columns={2:'identity_max'})
df = pd.merge(df, df_grouped, how='left', on=[0])
df = df[df[2] == df['identity_max']]

In [17]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,identity_max
0,1svr,1svq_A,1.00,94,0,0,1,94,10,103,8.723000e-58,196,1.00
1,1svr,1svy_A,1.00,94,0,0,1,94,10,103,8.723000e-58,196,1.00
2,1svr,1svr_A,1.00,94,0,0,1,94,10,103,8.723000e-58,196,1.00
3,1yagg,1yag_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
4,1yagg,1nmd_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
5,1yagg,1yvn_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
6,1yagg,1mdu_A,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
7,1yagg,1mdu_D,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
8,1yagg,1nlv_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
9,1yagg,1nm1_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
10,1yagg,3cjb_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
11,1yagg,3cjc_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
12,1yagg,3ci5_G,1.00,125,0,0,1,125,2,126,1.186000e-82,269,1.00
13,1yagg,1d4x_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
14,1yagg,5ubo_S,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
15,1yagg,3cip_G,1.00,125,0,0,1,125,4,128,1.186000e-82,269,1.00
16,1yagg,1p8z_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00
17,1yagg,2ff6_G,1.00,125,0,0,1,125,23,147,1.186000e-82,269,1.00
18,1yagg,2ff3_A,1.00,125,0,0,1,125,23,147,1.186000e-82,269,1.00
21,1yagg,5h3m_A,1.00,122,0,0,4,125,1,122,7.199000e-81,264,1.00
22,1yagg,5h3n_A,1.00,122,0,0,4,125,1,122,7.199000e-81,264,1.00
23,1yagg,5dd2_G,1.00,122,0,0,4,125,1,122,7.199000e-81,264,1.00
24,1yagg,5dd2_A,1.00,122,0,0,4,125,1,122,7.199000e-81,264,1.00
25,1yagg,5zz0_G,1.00,122,0,0,4,125,1,122,7.199000e-81,264,1.00
26,1yagg,5zz0_A,1.00,122,0,0,4,125,1,122,7.199000e-81,264,1.00
27,1yagg,1t44_G,1.00,122,0,0,4,125,4,125,7.199000e-81,264,1.00
52,1d0na1,6lje_A,0.94,101,6,0,8,108,1,101,1.642000e-60,205,0.94
53,1d0na1,6lje_B,0.94,101,6,0,8,108,1,101,1.642000e-60,205,0.94
54,1d0na1,6ljf_A,0.94,101,6,0,8,108,1,101,1.642000e-60,205,0.94
55,1d0na1,6ljf_B,0.94,101,6,0,8,108,1,101,1.642000e-60,205,0.94
57,2vil,2vik_A,1.00,126,0,0,1,126,1,126,1.558000e-81,266,1.00
58,2vil,2vil_A,1.00,126,0,0,1,126,1,126,1.558000e-81,266,1.00

In [11]:


# Hits presenting a best match that also have the same id name are prioritized
df["target_id_nochain"] = df[1].str.split("_",expand = True)[0]
df["target_id_chainmerged"] = df[1].str.replace("_", "").str.lower()



df_id_match_1 = df[df[0] == df["target_id_nochain"]]
df_id_match_2 = df[df[0] == df["target_id_chainmerged"]]
df_id_match = pd.concat([df_id_match_1,df_id_match_2])


# Only retain the dataframe
df_noid_match = df[~df[0].isin(df_id_match[0])].reset_index(drop = True)
if(not df_noid_match.empty):
    df_noid_match_filtered = df_noid_match.iloc[[df_noid_match[2].idxmax()]]
    final_df = pd.concat([df_id_match,df_noid_match_filtered])
else:
    final_df = df_id_match

In [12]:
final_df

,0,1,2,3,4,5,6,7,8,9,10,11,identity_max,target_id_nochain,target_id_chainmerged
2,1svr,1svr_A,1.00,94,0,0,1,94,10,103,8.723000e-58,196,1.00,1svr,1svra
58,2vil,2vil_A,1.00,126,0,0,1,126,1,126,1.558000e-81,266,1.00,2vil,2vila
3,1yagg,1yag_G,1.00,125,0,0,1,125,1,125,1.186000e-82,269,1.00,1yag,1yagg
0,1d0na1,6lje_A,0.94,101,6,0,8,108,1,101,1.642000e-60,205,0.94,6lje,6ljea